# Generated by Django 6.0 on 2025-12-25 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cardholder_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('expiration_month', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, null=True)),
                ('expiration_year', models.CharField(blank=True, max_length=2, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'core_paymentmethod',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'card_number')},
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invoice', models.CharField(max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('standard', 'Standard'), ('team', 'Team'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='business', max_length=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('no_charge', 'No Charge')], default='pending', max_length=9)),
                ('currency', models.CharField(choices=[('EUR', 'Euros'), ('USD', 'Dollars'), ('GBP', 'British Pound')], default='EUR', max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings_used', to='billing.paymentmethod')),
            ],
            options={
                'verbose_name': 'Billing Record',
                'verbose_name_plural': 'Billing Records',
                'db_table': 'billing',
                'ordering': ['-billing_period_start'],
                'indexes': [models.Index(fields=['invoice'], name='billing_invoice_7388e5_idx')],
            },
        ),
    ]
