# version: "3.9" --> obsolete

services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  questionnaire:
    build:
      context: ./questionnaire
      dockerfile: Dockerfile
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./questionnaire:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  qcluster:
    build: .
    command: python manage.py qcluster
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
  static_volume: