# Generated by Django 5.2.6 on 2025-10-02 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_dataset_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invoice', models.CharField(max_length=100, unique=True)),
                ('plan_type', models.CharField(choices=[('standard', 'Standard'), ('team', 'Team'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='business', max_length=10)),
                ('payment_method', models.CharField(choices=[('CC', 'Credit Card'), ('PP', 'PayPal'), ('BT', 'Bank Transfer')], default='CC', max_length=2)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('no_charge', 'No Charge')], default='pending', max_length=9)),
                ('currency', models.CharField(choices=[('EUR', 'Euros'), ('USD', 'Dollars'), ('GBP', 'British Pound')], default='EUR', max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Record',
                'verbose_name_plural': 'Billing Records',
                'db_table': 'billing',
                'ordering': ['-billing_period_start'],
            },
        ),
    ]
