# Generated by Django 5.2.6 on 2025-10-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_billing_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dataset', 'verbose_name_plural': 'Datasets'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
