# Generated by Django 5.2.6 on 2025-10-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_add_Meta_at_users'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['invoice'], name='billing_invoice_7388e5_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['name'], name='dataset_name_716457_idx'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['name'], name='experiment_name_aaa840_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
    ]
