# Generated by Django 5.2.6 on 2025-10-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='core_user_email_38052c_idx',
            old_name='user_email_7bbb4c_idx',
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
