# Generated by Django 5.2.7 on 2025-10-15 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_dataset_label_alter_dataset_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_payment_method_id', models.CharField(help_text='ID for this specific payment method at the payment gateway', max_length=255, unique=True)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('expiration_month', models.IntegerField(blank=True, null=True)),
                ('expiration_year', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'gateway_payment_method_id')},
            },
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_method_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings_used', to='core.paymentmethod'),
        ),
    ]
