# Generated by Django 5.2.7 on 2025-11-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_billing_payment_method_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cvv',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiration_month',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user', 'card_number')},
        ),
    ]
