# Generated by Django 5.2.7 on 2025-11-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_paymentmethod_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='gateway_payment_method_id',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='last4',
        ),
    ]
