# Generated by Django 6.0 on 2025-12-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_dataset_size_gb'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billing',
            name='billing_invoice_7388e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='dataset',
            name='dataset_name_716457_idx',
        ),
        migrations.RemoveIndex(
            model_name='experiment',
            name='experiment_name_aaa840_idx',
        ),
        migrations.RemoveConstraint(
            model_name='experimentcollaborator',
            name='unique_person_experiment',
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profile_user_id_2c597b_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='core_user_email_38052c_idx',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='experiments',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='users',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='experimentcollaborator',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='experimentcollaborator',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
        migrations.DeleteModel(
            name='ExperimentCollaborator',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
