# Generated by Django 6.0 on 2026-04-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('stage', models.IntegerField(choices=[(1, 'Scope'), (2, 'Your Legal Role'), (3, 'Exlusions from the scope of AI'), (4, 'Risk classification'), (5, 'High Risk'), (6, 'Limited Risk'), (7, 'Minimal Risk')], default=1, verbose_name='Question Stage')),
                ('is_multiple_choice', models.BooleanField(default=False, verbose_name='Allow Multiple Choices')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('introduction_text', models.TextField(blank=True, help_text='Text shown before starting the questionnaire.', verbose_name='Introduction Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI System Questionnaire',
                'verbose_name_plural': 'AI System Questionnaires',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Choice Text')),
                ('is_out_of_scope', models.BooleanField(default=False, help_text='Αν επιλεγεί, τερματίζει το τεστ ως Out of Scope')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_choices', to='questionnaire.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questionnaires', to='questionnaire.questionnaire')),
            ],
            options={
                'verbose_name': 'Sub Questionnaire',
                'verbose_name_plural': 'Sub Questionnaires',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='sub_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.subquestionnaire'),
        ),
    ]
