# Generated by Django 6.0 on 2026-04-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_classification', models.CharField(max_length=100)),
                ('full_responses_dump', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(help_text='The ID from questions.json (e.g. 1.1.1)', max_length=100, primary_key=True, serialize=False)),
                ('top_label', models.CharField(blank=True, help_text="Π.χ. 'Scope: Yes' ή 'Role: Provider'", max_length=100, null=True, verbose_name='Top Label Text')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('help_text', models.TextField(blank=True, help_text='Additional information about the question', null=True, verbose_name='Help Text')),
                ('result_text', models.TextField(blank=True, help_text='If the question is a summary type, the final result text is entered here.', null=True, verbose_name='Result/Summary Text')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('stage', models.IntegerField(choices=[(1, 'Scope'), (2, 'Your Legal Role'), (3, 'Exclusions from the scope of AI'), (4, 'Risk classification'), (5, 'High Risk'), (6, 'Limited Risk'), (7, 'Minimal Risk')], default=1, verbose_name='Question Stage')),
                ('answer_type', models.CharField(choices=[('yes/no', 'Yes/No'), ('multiple', 'Multiple Choice'), ('summary', 'Summary/Result'), ('acknowledgment', 'Acknowledgment')], default='yes/no', max_length=50, verbose_name='Answer Type')),
                ('is_multiple_choice', models.BooleanField(default=False, verbose_name='Allow Multiple Choices')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('introduction_text', models.TextField(blank=True, help_text='Text shown before starting the questionnaire.', verbose_name='Introduction Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI System Questionnaire',
                'verbose_name_plural': 'AI System Questionnaires',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Choice Text')),
                ('is_out_of_scope', models.BooleanField(default=False, help_text='If selected, ends the test as Out of Scope')),
                ('is_assessment_completed', models.BooleanField(default=False, help_text='If selected, ends the test with the message Assessment Completed (Energy Guard)')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_choices', to='questionnaire.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questionnaires', to='questionnaire.questionnaire')),
            ],
            options={
                'verbose_name': 'Sub Questionnaire',
                'verbose_name_plural': 'Sub Questionnaires',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='sub_questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.subquestionnaire'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
                ('selected_choices', models.ManyToManyField(to='questionnaire.choice')),
            ],
            options={
                'unique_together': {('session_key', 'question')},
            },
        ),
    ]
