# Generated by Django 6.0 on 2026-05-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestionnaire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
