# Generated by Django 6.0 on 2026-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_assessment_completed',
            field=models.BooleanField(default=False, help_text='Αν επιλεγεί, τερματίζει το τεστ με το μήνυμα Assessment Completed (Energy Guard)'),
        ),
    ]
