# Generated by Django 6.0 on 2026-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_choice_is_assessment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='top_label',
            field=models.CharField(blank=True, help_text="Π.χ. 'Scope: Yes' ή 'Role: Provider'", max_length=100, null=True, verbose_name='Top Label Text'),
        ),
    ]
