# Generated by Django 6.0 on 2026-04-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_question_top_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('yes/no', 'Yes/No'), ('multiple', 'Multiple Choice'), ('summary', 'Summary/Result'), ('acknowledgment', 'Acknowledgment')], default='yes/no', max_length=50, verbose_name='Answer Type'),
        ),
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.TextField(blank=True, help_text='Επιπλέον πληροφορίες για την ερώτηση', null=True, verbose_name='Help Text'),
        ),
        migrations.AddField(
            model_name='question',
            name='result_text',
            field=models.TextField(blank=True, help_text='Αν η ερώτηση είναι τύπου summary, εδώ μπαίνει το τελικό κείμενο αποτελέσματος.', null=True, verbose_name='Result/Summary Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(help_text='Το ID από το questions.json (π.χ. 1.1.1)', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Scope'), (2, 'Your Legal Role'), (3, 'Exclusions from the scope of AI'), (4, 'Risk classification'), (5, 'High Risk'), (6, 'Limited Risk'), (7, 'Minimal Risk')], default=1, verbose_name='Question Stage'),
        ),
    ]
