# Generated by Django 6.0 on 2026-04-27 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_alter_question_options_question_answer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_assessment_completed',
            field=models.BooleanField(default=False, help_text='If selected, ends the test with the message Assessment Completed (Energy Guard)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_out_of_scope',
            field=models.BooleanField(default=False, help_text='If selected, ends the test as Out of Scope'),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=models.TextField(blank=True, help_text='Additional information about the question', null=True, verbose_name='Help Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(help_text='The ID from questions.json (e.g. 1.1.1)', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='result_text',
            field=models.TextField(blank=True, help_text='If the question is a summary type, the final result text is entered here.', null=True, verbose_name='Result/Summary Text'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
                ('selected_choices', models.ManyToManyField(to='questionnaire.choice')),
            ],
        ),
    ]
