# Generated by Django 6.0 on 2026-04-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_alter_choice_is_assessment_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_classification', models.CharField(max_length=100)),
                ('full_responses_dump', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
