# Generated by Django 6.0 on 2026-07-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_subquestionnaire_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.JSONField(default=list)),
                ('track_results', models.JSONField(default=dict)),
                ('answers', models.JSONField(default=dict)),
                ('checklist_status', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'AI Act Assessment',
                'verbose_name_plural': 'AI Act Assessments',
            },
        ),
    ]
