# Generated by Django 6.0 on 2026-01-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, choices=[('Amazon', 'Amazon'), ('Microsoft', 'Microsoft'), ('Google', 'Google'), ('Facebook', 'Facebook'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
