# Generated by Django 6.0 on 2026-02-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="company",
            new_name="team",
        ),
    ]
