# Generated by Django 6.0 on 2026-03-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_alter_profile_team_team_team_name_53aa8f_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='creator',
        ),
        migrations.AddField(
            model_name='profile',
            name='team_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('member', 'Member')], default=None, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('team_role', 'admin')), fields=('team',), name='unique_team_admin'),
        ),
    ]
