# Generated by Django 6.0 on 2026-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_team_creator_profile_team_role_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('team__isnull', True), ('team_role__isnull', True)), models.Q(('team__isnull', False), ('team_role__isnull', False)), _connector='OR'), name='team_and_role_together_or_both_null'),
        ),
    ]
