# Generated by Django 6.0 on 2026-03-03 12:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_team_and_role_together_or_both_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.Profile.profile_pic_upload_to),
        ),
    ]
