# Generated by Django 6.0 on 2026-03-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
