# Generated by Django 6.0 on 2026-08-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_team_joined_at_to_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx'),
        ),
    ]
