# Generated by Django 6.0 on 2026-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltwins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtresult',
            name='bucket_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
