# Generated by Django 6.0 on 2026-09-07 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltwins', '0002_dtresult_bucket_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RdnSimulationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rdn_request_id', models.PositiveIntegerField(unique=True)),
                ('use_case', models.CharField(max_length=50)),
                ('grid_section', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdn_simulation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RDN Simulation Job',
                'verbose_name_plural': 'RDN Simulation Jobs',
                'db_table': 'rdn_simulation_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
