# Generated by Django 6.0 on 2026-09-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltwins', '0004_schedule_reconcile_stale_rdn_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdnsimulationjob',
            name='rdn_request_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
