# Generated by Django 6.0 on 2026-09-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltwins', '0005_alter_rdnsimulationjob_rdn_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdnsimulationjob',
            name='assets',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
