# Generated by Django 6.0 on 2026-09-08 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltwins', '0006_rdnsimulationjob_assets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BerExperimentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment_json', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ber_experiment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BER Experiment Request',
                'verbose_name_plural': 'BER Experiment Requests',
                'db_table': 'ber_experiment_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
