# Generated by Django 6.0 on 2026-09-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaltwins', '0008_rdnsimulationjob_result_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berexperimentrequest',
            options={'ordering': ['-created_at'], 'permissions': [('manage_ber_requests', 'Can manage BER experiment requests')], 'verbose_name': 'BER Experiment Request', 'verbose_name_plural': 'BER Experiment Requests'},
        ),
        migrations.AddField(
            model_name='berexperimentrequest',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berexperimentrequest',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berexperimentrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='berexperimentrequest',
            name='result_key',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
