# Generated by Django 6.0 on 2026-06-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustworthiness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20),
        ),
    ]
