# Generated by Django 6.0 on 2026-06-25 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustworthiness', '0003_schedule_stale_assessment_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='parent_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='trustworthiness.assessment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
